import { Grant, LogEntry } from '../types';
import { v4 as uuidv4 } from 'uuid';

export const generateEmailBody = (grants: Grant[]): string => {
  if (grants.length === 0) return "No new grants discovered.";

  const header = `GRANT DISCOVERY REPORT\nGenerated: ${new Date().toLocaleString()}\n\nFound ${grants.length} new opportunities:\n\n`;
  
  const items = grants.map((g, i) => {
    return `[${i + 1}] ${g.program_title.toUpperCase()}
   Agency:   ${g.agency_name}
   Status:   ${g.status}
   Deadline: ${g.application_deadline || 'Not specified'}
   Amount:   ${g.funding_amount || 'Not specified'}
   
   Summary:
   ${g.brief_description}
   
   APPLY HERE: ${g.official_application_link}
   ------------------------------------------------------------`;
  }).join('\n\n');

  const footer = `\n\n--\nGenerated by GrantHunter AI`;

  return header + items + footer;
};

export const sendNotification = async (
    email: string, 
    grants: Grant[], 
    onLog: (log: LogEntry) => void
): Promise<void> => {
    if (!email || grants.length === 0) return;

    const log = (msg: string, level: LogEntry['level'] = 'INFO') => {
        onLog({
            id: uuidv4(),
            timestamp: new Date().toLocaleTimeString(),
            level,
            message: msg
        });
    };

    log(`Preparing notification summary for ${grants.length} items...`);

    // Simulate network delay for email service
    await new Promise(resolve => setTimeout(resolve, 800));
    
    log(`Connecting to SMTP Relay (Simulated)...`);
    await new Promise(resolve => setTimeout(resolve, 600));

    // In a real production app, this would be an API call, e.g.:
    // await fetch('/api/email', { method: 'POST', body: JSON.stringify({ to: email, grants }) });
    
    // For client-side demo, we log the success and formatted body to console
    const body = generateEmailBody(grants);
    console.groupCollapsed(`📧 Email Sent to ${email}`);
    console.log(body);
    console.groupEnd();

    log(`Email successfully dispatched to ${email}`, 'SUCCESS');
};
